import Head from 'next/head'
import { useRouter } from "next/router";

import styles from "@/styles/Users.module.css";
import { CardPaper, CardHead, CardContent } from "@/components/Card";
import List from "@/components/List";

function Users({ usernames }) {
  const router = useRouter();

  if (router.isFallback) {
    return <div>Loading...</div>;
  }

  const data = usernames.map(username => ({
    title: username,
    link: `/users/${username}/repos`
  }));

  return (
    <div className={styles.container}>
      <Head>
        <title>Dcard 2022 Intern Homework</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <CardPaper variant="round">
          <CardHead>Users</CardHead>
          <CardContent>
            <List data={data} />
          </CardContent>
        </CardPaper>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const response = await fetch(`http://localhost:3000/api/usernames`);
  const { usernames } = await response.json();

  return {
    props: { usernames },
    revalidate: 1
  };
}

export default Users;
